version: "3"
services:
  api:
    build: .
    ports:
      - 8002:8002
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/fastify_crud
      - JWT_SECRET=your-secret-key-change-in-production-09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastify_crud
    volumes:
      - postgres-fastify-db:/var/lib/postgresql/data

volumes:
  postgres-fastify-db:

